/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuvenlikRouteImport } from './routes/guvenlik'
import { Route as KaynaklarRouteImport } from './routes/kaynaklar'
import { Route as MalzemeRouteImport } from './routes/malzeme'
import { Route as OlcmeRouteImport } from './routes/olcme'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as HaftaWeekRouteImport } from './routes/hafta.$week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenlikRoute = GuvenlikRouteImport.update({
  id: '/guvenlik',
  path: '/guvenlik',
  getParentRoute: () => rootRouteImport,
} as any)
const KaynaklarRoute = KaynaklarRouteImport.update({
  id: '/kaynaklar',
  path: '/kaynaklar',
  getParentRoute: () => rootRouteImport,
} as any)
const MalzemeRoute = MalzemeRouteImport.update({
  id: '/malzeme',
  path: '/malzeme',
  getParentRoute: () => rootRouteImport,
} as any)
const OlcmeRoute = OlcmeRouteImport.update({
  id: '/olcme',
  path: '/olcme',
  getParentRoute: () => rootRouteImport,
} as any)
const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const HaftaWeekRoute = HaftaWeekRouteImport.update({
  id: '/hafta/$week',
  path: '/hafta/$week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guvenlik': typeof GuvenlikRoute
  '/kaynaklar': typeof KaynaklarRoute
  '/malzeme': typeof MalzemeRoute
  '/olcme': typeof OlcmeRoute
  '/takvim': typeof TakvimRoute
  '/hafta/$week': typeof HaftaWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guvenlik': typeof GuvenlikRoute
  '/kaynaklar': typeof KaynaklarRoute
  '/malzeme': typeof MalzemeRoute
  '/olcme': typeof OlcmeRoute
  '/takvim': typeof TakvimRoute
  '/hafta/$week': typeof HaftaWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guvenlik': typeof GuvenlikRoute
  '/kaynaklar': typeof KaynaklarRoute
  '/malzeme': typeof MalzemeRoute
  '/olcme': typeof OlcmeRoute
  '/takvim': typeof TakvimRoute
  '/hafta/$week': typeof HaftaWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guvenlik'
    | '/kaynaklar'
    | '/malzeme'
    | '/olcme'
    | '/takvim'
    | '/hafta/$week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guvenlik'
    | '/kaynaklar'
    | '/malzeme'
    | '/olcme'
    | '/takvim'
    | '/hafta/$week'
  id:
    | '__root__'
    | '/'
    | '/guvenlik'
    | '/kaynaklar'
    | '/malzeme'
    | '/olcme'
    | '/takvim'
    | '/hafta/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuvenlikRoute: typeof GuvenlikRoute
  KaynaklarRoute: typeof KaynaklarRoute
  MalzemeRoute: typeof MalzemeRoute
  OlcmeRoute: typeof OlcmeRoute
  TakvimRoute: typeof TakvimRoute
  HaftaWeekRoute: typeof HaftaWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guvenlik': {
      id: '/guvenlik'
      path: '/guvenlik'
      fullPath: '/guvenlik'
      preLoaderRoute: typeof GuvenlikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaynaklar': {
      id: '/kaynaklar'
      path: '/kaynaklar'
      fullPath: '/kaynaklar'
      preLoaderRoute: typeof KaynaklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malzeme': {
      id: '/malzeme'
      path: '/malzeme'
      fullPath: '/malzeme'
      preLoaderRoute: typeof MalzemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olcme': {
      id: '/olcme'
      path: '/olcme'
      fullPath: '/olcme'
      preLoaderRoute: typeof OlcmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hafta/$week': {
      id: '/hafta/$week'
      path: '/hafta/$week'
      fullPath: '/hafta/$week'
      preLoaderRoute: typeof HaftaWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuvenlikRoute: GuvenlikRoute,
  KaynaklarRoute: KaynaklarRoute,
  MalzemeRoute: MalzemeRoute,
  OlcmeRoute: OlcmeRoute,
  TakvimRoute: TakvimRoute,
  HaftaWeekRoute: HaftaWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
